spring:
  application:
    name: default
  cloud:
    config:
      uri: http://localhost:${config.port:8888}

logging:
  levels:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.cloud.config.server: DEBUG